### ISSUE TITLE
寻求商务合作

### ISSUE THREAD

**Issue by specialzxw** [douzhongqiang/EasyCanvas#2]
hi，我们对您分享的这个项目十分感兴趣，您的专业技术十分出色，我们想与您进行商务合作，但是github上没有留下您的联系方式，可以在这里留下您的邮箱或微信，方便我们与您建立联系吗？

**Comment by douzhongqiang** [comment]
qq: 514200399
邮箱：514200399@qq.com




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "douzhongqiang/EasyCanvas"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月4日(星期五) 下午3:00
收件人:&nbsp;"douzhongqiang/EasyCanvas"<EasyCanvas@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[douzhongqiang/EasyCanvas] 寻求商务合作 (#2)





 
hi，我们对您分享的这个项目十分感兴趣，您的专业技术十分出色，我们想与您进行商务合作，但是github上没有留下您的联系方式，可以在这里留下您的邮箱或微信，方便我们与您建立联系吗？

**Comment by douzhongqiang** [comment]
> hi，我们对您分享的这个项目十分感兴趣，您的专业技术十分出色，我们想与您进行商务合作，但是github上没有留下您的联系方式，可以在这里留下您的邮箱或微信，方便我们与您建立联系吗？

qq: 514200399
