### ISSUE TITLE
pythonQT-Qt5-python38的库不能定位程序输入点

### ISSUE THREAD

**Issue by SurnameX** [douzhongqiang/EasyCanvas#3]
环境
系统：win10 企业版，LTSC 1809
编译器：msvc2017_64
Qt版本：5.14.2

问题：编译都通过了，并生成了exe，但是调试运行找不到程序输入点在PythonQt_QtAll-Qt5-Python38，setItemData这个函数定位不了。
然后使用编译好的exe，拷贝到打包好的目录，可以直接运行。

什么原因，是字符编码的问题吗？
所做的更改：所有的pro被我加上了 utf-8 识别，否则会编译失败。

建议：希望作者加个自己的环境介绍，以及推荐的环境。虽不可能多种环境测试，但是做一个环境介绍及推荐环境，可以让别人快速编译使用到源码。

**Comment by douzhongqiang** [comment]
不好意思，我确实没有注明开发环境得版本信息。
目前使用的Qt5.13和VS2015，代码中的库也都是基于这个环境得64位的。
您的这个环境需要自己编译pythonqt，然后替换项目中库的使用位置就可以了。
github对应的介绍，我稍后会补上。
