### ISSUE TITLE
m_pCurrentOper 内存泄漏问题解决

### ISSUE THREAD

**Issue by saku-ze** [douzhongqiang/EasyCanvas#6]
EasyCanvasCore/UICanvas/UICanvasView.cpp b/EasyCanvasCore/UICanvas/UICanvasView.h 中 m_pCurrentOper 指针存在内存泄漏

建议如下修改：
```patch
diff --git a/EasyCanvasCore/UICanvas/UICanvasView.cpp b/EasyCanvasCore/UICanvas/UICanvasView.cpp
index b936367..9ff3fc6 100644
--- a/EasyCanvasCore/UICanvas/UICanvasView.cpp
+++ b/EasyCanvasCore/UICanvas/UICanvasView.cpp
@@ -87,7 +87,8 @@ void UICanvasView::setSelectedRect(const QRect& rect)
 
 void UICanvasView::setCurrentOperator(UICanvasOperBase* canvasOper)
 {
-    m_pCurrentOper = canvasOper;
+    m_pCurrentOper.reset();
+    m_pCurrentOper = std::make_shared<UICanvasOperBase>(canvasOper);
 }
 
 void UICanvasView::mousePressEvent(QMouseEvent* event)
diff --git a/EasyCanvasCore/UICanvas/UICanvasView.h b/EasyCanvasCore/UICanvas/UICanvasView.h
index da69da5..bd575cb 100644
--- a/EasyCanvasCore/UICanvas/UICanvasView.h
+++ b/EasyCanvasCore/UICanvas/UICanvasView.h
@@ -4,6 +4,7 @@
 #include <QGraphicsView>
 #include <QGraphicsScene>
 #include "easycanvascore_global.h"
+#include <memory>
 
 class UICanvasOperBase;
 class UICanvasPathItem;
@@ -82,7 +83,7 @@ private:
     UICanvasScene* m_pScene = nullptr;
 
     UICanvasPathItem* m_pathItem = nullptr;
-    UICanvasOperBase* m_pCurrentOper = nullptr;
+    std::shared_ptr<UICanvasOperBase> m_pCurrentOper(nullptr);
 
     // 选中矩形相关
     bool m_isSelectedRectVisible = false;

```

**Comment by douzhongqiang** [comment]
> EasyCanvasCore/UICanvas/UICanvasView.cpp b/EasyCanvasCore/UICanvas/UICanvasView.h 中 m_pCurrentOper 指针存在内存泄漏
> 
> 建议如下修改：
> 
> ```diff
> diff --git a/EasyCanvasCore/UICanvas/UICanvasView.cpp b/EasyCanvasCore/UICanvas/UICanvasView.cpp
> index b936367..9ff3fc6 100644
> --- a/EasyCanvasCore/UICanvas/UICanvasView.cpp
> +++ b/EasyCanvasCore/UICanvas/UICanvasView.cpp
> @@ -87,7 +87,8 @@ void UICanvasView::setSelectedRect(const QRect& rect)
>  
>  void UICanvasView::setCurrentOperator(UICanvasOperBase* canvasOper)
>  {
> -    m_pCurrentOper = canvasOper;
> +    m_pCurrentOper.reset();
> +    m_pCurrentOper = std::make_shared<UICanvasOperBase>(canvasOper);
>  }
>  
>  void UICanvasView::mousePressEvent(QMouseEvent* event)
> diff --git a/EasyCanvasCore/UICanvas/UICanvasView.h b/EasyCanvasCore/UICanvas/UICanvasView.h
> index da69da5..bd575cb 100644
> --- a/EasyCanvasCore/UICanvas/UICanvasView.h
> +++ b/EasyCanvasCore/UICanvas/UICanvasView.h
> @@ -4,6 +4,7 @@
>  #include <QGraphicsView>
>  #include <QGraphicsScene>
>  #include "easycanvascore_global.h"
> +#include <memory>
>  
>  class UICanvasOperBase;
>  class UICanvasPathItem;
> @@ -82,7 +83,7 @@ private:
>      UICanvasScene* m_pScene = nullptr;
>  
>      UICanvasPathItem* m_pathItem = nullptr;
> -    UICanvasOperBase* m_pCurrentOper = nullptr;
> +    std::shared_ptr<UICanvasOperBase> m_pCurrentOper(nullptr);
>  
>      // 选中矩形相关
>      bool m_isSelectedRectVisible = false;
> ```

感谢你得建议，代码已修改。
